[project]
name = "route2gpx"
version = "0.1.0"
description = "Convert Google Routes API routes to GPX files."
license = "MIT"
authors = [
    {name = "robert-bryson",email = "rsmbryson@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "python-dotenv (>=1.2.0,<2.0.0)",
    "polyline (>=2.0.4,<3.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
isort = "^8.0.1"
pytest = "^9.1.0"
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
